graph TD
    %% Entitas Sumber / Input
    subgraph Sisi Lapangan & Publik
        U_Masyarakat[Masyarakat Umum]
        U_Kader[Kader / Nasabah Bank Sampah]
        U_Petugas[Petugas Pengangkut]
    end

    %% Antarmuka PWA / Web Terdistribusi
    subgraph PWA & Portals
        P_Portal[Portal Publik & Form Aduan]
        P_Mobile[PWA Operasional Mobile]
        DB_Local[(Local IndexedDB\nOffline Cache)]
        
        U_Kader -.->|"Input Pilah/Masuk"| P_Mobile
        U_Petugas -.->|"Input Residu/Angkut"| P_Mobile
        P_Mobile <-->|"Simpan/Baca Offline"| DB_Local
        
        U_Masyarakat -.->|"Kirim Laporan Aduan"| P_Portal
    end

    %% Sisi Cloud / Server
    subgraph Backend & Real-Time Sync
        API[API / Service Layer]
        DB_Cloud[(Central Cloud Database)]
        
        DB_Local == "Auto Sync saat Online" ==> API
        P_Portal --> API
        API <--> DB_Cloud
    end

    %% Dasbor dan Pengolahan Lanjutan
    subgraph Management Dashboard
        D_GIS[Dashboard GIS & Heatmap]
        D_Exec[Dashboard Eksekutif DLHK]
        
        DB_Cloud --> D_GIS
        DB_Cloud --> D_Exec
    end

    %% Pengguna Sistem Pusat
    U_Pemdes[Pemerintah Desa / Pemdes] --> D_GIS
    U_Dinas[Dinas Eksekutif] --> D_Exec
    U_Dinas --> D_GIS

    %% Tindakan Lanjutan
    D_Exec -->|"Export File CSV/Excel"| SIPSN["Sistem Pelaporan SIPSN Nasional"]
